#!/usr/bin/env python
import os
virtenv = os.environ['OPENSHIFT_HOMEDIR'] + '/python-2.7/virtenv'
os.environ['PYTHON_EGG_CACHE'] = '/tmp'
os.environ['PATH'] = os.environ['PATH'] +','+ os.environ['OPENSHIFT_REPO_DIR'] +'/wsgi'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from demo import app as application

